-- MySQL Script generated by MySQL Workbench
-- Tue Jan 12 23:41:24 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema electro956_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `electro956_db` ;

-- -----------------------------------------------------
-- Schema electro956_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `electro956_db` DEFAULT CHARACTER SET utf8 ;
USE `electro956_db` ;

-- -----------------------------------------------------
-- Table `electro956_db`.`Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electro956_db`.`Post` ;

CREATE TABLE IF NOT EXISTS `electro956_db`.`Post` (
  `postID` VARCHAR(45) NOT NULL COMMENT '',
  `title` VARCHAR(51) NULL COMMENT '',
  `content` VARCHAR(251) NULL COMMENT '',
  `time` MEDIUMTEXT NULL COMMENT '',
  `userID` VARCHAR(45) NULL COMMENT '',
  `endTime` VARCHAR(45) NULL COMMENT '',
  `deleted` VARCHAR(45) NULL DEFAULT 'false' COMMENT '',
  `spamcount` INT NULL DEFAULT 0 COMMENT '',
  `spam` VARCHAR(45) NULL DEFAULT 'false' COMMENT '',
  PRIMARY KEY (`postID`),
  UNIQUE INDEX `postID_UNIQUE` (`postID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electro956_db`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electro956_db`.`User` ;

CREATE TABLE IF NOT EXISTS `electro956_db`.`User` (
  `userID` VARCHAR(45) NOT NULL COMMENT '',
  `firstName` VARCHAR(45) NULL COMMENT '',
  `lastName` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(256) NULL COMMENT '',
  `userName` VARCHAR(45) NULL COMMENT '',
  `bio` VARCHAR(500) NULL COMMENT '',
  `spamcount` INT NULL DEFAULT 0 COMMENT '',
  `Usercol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electro956_db`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electro956_db`.`Message` ;

CREATE TABLE IF NOT EXISTS `electro956_db`.`Message` (
  `messageID` VARCHAR(45) NOT NULL COMMENT '',
  `content` VARCHAR(256) NULL COMMENT '',
  `fromID` VARCHAR(45) NULL COMMENT '',
  `toID` VARCHAR(45) NULL COMMENT '',
  `time` MEDIUMTEXT NULL COMMENT '',
  `viewed` VARCHAR(45) NULL COMMENT '',
  `postID` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`messageID`),
  UNIQUE INDEX `messageID_UNIQUE` (`messageID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electro956_db`.`UserLocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electro956_db`.`UserLocation` ;

CREATE TABLE IF NOT EXISTS `electro956_db`.`UserLocation` (
  `userID` VARCHAR(45) NOT NULL COMMENT '',
  `latitude` VARCHAR(45) NULL COMMENT '',
  `longitude` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electro956_db`.`PostLocation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electro956_db`.`PostLocation` ;

CREATE TABLE IF NOT EXISTS `electro956_db`.`PostLocation` (
  `postID` VARCHAR(45) NOT NULL COMMENT '',
  `latitude` VARCHAR(45) NULL COMMENT '',
  `longitude` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`postID`),
  UNIQUE INDEX `userID_UNIQUE` (`postID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electro956_db`.`UserMap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electro956_db`.`UserMap` ;

CREATE TABLE IF NOT EXISTS `electro956_db`.`UserMap` (
  `userName` VARCHAR(45) NOT NULL COMMENT '',
  `userID` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`userName`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electro956_db`.`UserImage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electro956_db`.`UserImage` ;

CREATE TABLE IF NOT EXISTS `electro956_db`.`UserImage` (
  `userID` VARCHAR(45) NOT NULL COMMENT '',
  `userImageSmall` LONGTEXT NULL COMMENT '',
  `UserImageLarge` LONGTEXT NULL COMMENT '',
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
